[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[solc]
version = "0.8.20"

remappings = ['@openzeppelin-contracts/contracts=lib/openzeppelin-contracts/contract']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config